### ISSUE TITLE
latest Python version needed ?

### ISSUE THREAD

**Issue by tissatussa** [akashi-org/akashi#50]
hi,

i just discovered your Akashi "next-generation video editor" .. the project seems in an early stage but i'm curious .. however, i need Python >= 3.10 to run it, and i have v3.9.7 on my Xubuntu 21.10 .. so, i found this doc : 

Upgrade Python to latest version (3.10) on Ubuntu Linux
https://cloudbytes.dev/snippets/upgrade-python-to-latest-version-on-ubuntu-linux

is it save to upgrade Python like this ?
the (X)ubuntu system heavily depends on it !

anyhow, why is >= 3.10 needed ?
why can't an older v3 be used ?  i guess Akashi uses very new functions / modules ..

**Comment by crux14** [comment]
Thank you so much for your interest in Akashi.

First of all, what I want to make clear is that this project is in the very early stage and not yet ready for testing. So I'm afraid to say that **you can't test Akashi as for now**. 

Right now I'm working on preparing for an upcoming release with which you will be able to test Akashi in your local machine. I hope to have the release **by the end of this month or the beginning of next month**.

Below, I'll answer the questions in your comment.

> is it save(safe?) to upgrade Python like this ?

I'm not perfectly sure what you mean, but if that means upgrading the system python by using apt, **I would not recommend it**. Or rather, I'd recommend pyenv. With pyenv, you can safely manage multiple Python versions with no risks.

> anyhow, why is >= 3.10 needed ?

Since Python3.7, many syntactic changes have been introduced. I believe that these changes are basically preferable or necessary for Python users, especially users who use typing severely. Akashi is designed to be used with typing, so I'd like to incorporate these changes as much as possible. So, Akashi currently targets only the latest stable version. (This policy can be revised in the near future, though.)

**Comment by tissatussa** [comment]
thanks for the reply.
yes, i meant to write saFe .. so your advice to not-upgrade Python but to use pyenv, is appreciated !
